patient_name: "adolescent#002"
sensor_name: "Dexcom"
pump_name: "Insulet"
scenario: 
      - - 7
        - 45
      - - 12
        - 70
      - - 16
        - 15
      - - 18
        - 80
      - - 23
        - 10
hours: 24
priors_data_file: "all_patients_params.json"
inflation_factor: 1.5
mean_shift: 0.2
prior_type: 'uniform'

sbi_settings:
  algorithm: TSNPE
  sampling_method: 'sir'
  num_simulations: 15000
  num_rounds: 5
  n_samples_from_posterior: 1000

number_of_params: 45


