hours: 24
infer_meal_params: true
patient_name: adolescent#002
prior_settings:
  inflation_factor: 1.2
  mean_shift: 0.2
  number_of_params: 2
  prior_type: uniform
  priors_data_file: all_sg_patients_params_values.json
pump_name: Insulet
sbi_settings:
  algorithm: TSNPE
  n_samples_from_posterior: 100
  num_rounds: 3
  num_simulations: 100
  sample_proposal_with: sir
  sampling_method: direct
scenario:
- - 7
  - 45
- - 12
  - 70
- - 16
  - 15
- - 18
  - 80
- - 23
  - 10
sensor_name: Dexcom
simulate_posterior_hours: 24
