patient_name: "adolescent#002"
sensor_name: "Dexcom"
pump_name: "Insulet"
scenario:
      - - 7
        - 45
      - - 12
        - 70
      - - 16
        - 15
      - - 18
        - 80
      - - 23
        - 10
hours: 24

prior_settings:
  priors_data_file: "all_sg_patients_params_values.json"
  inflation_factor: 1
  mean_shift: 0
  prior_type: 'mvn'
  number_of_params: 5

sbi_settings:
  algorithm: BayesFlow
  sampling_method: 'sir'
  num_simulations: 10
  num_rounds: 1
  n_samples_from_posterior: 10

simulate_posterior_hours: 24
